### PR TITLE
Update ping command

### PR DESCRIPTION
**Pull request by Chensokheng**
@Daanisaanwezig  Here is the changed I have made. You can check it.

Happy Hacktoberfest. 👩‍💻

### CODE REVIEW

**Comment by Daanisaanwezig** [comment]
Perfect, there is one small thing tho. You can obtain the ping faster because it is already stored in the client/bot object. You can retrieve it using `client.ws.ping`, this wil return the ping in milliseconds. If you want to change it feel free to do so, if not I will merge it regardless.

**Comment by Chensokheng** [comment]
@Daanisaanwezig  I am not sure whether this correct or not. I have checked the bot object. I see the attribute pings. So here what I will change and I have checked it. It is faster than previous  code. 
```js
module.exports.run = async (bot, message, args) => {
  message.channel.send(`**:ping_pong: Pong! Your Ping Is:** ${bot.pings}ms`);
};
```
If this one is also correct. I will make the change now. 🙏

**Comment by Daanisaanwezig** [comment]
Sorry I think I didn't explain it well enough. The ping to the Discord api servers (and thus the times it takes for a command to go through) is stored in `.ws.ping` in the client/bot user object. 
So in this case because `bot` is used to define the user that is the bot you could send the variable `bot.ws.ping` in a channel and it will show the ping of the bot.
The reason why you want to obtain it like this instead of comparing the time the message was send with the current time is because it is possible that one of the 2 (or both) are not synchronized with the actual current time. You should even be able to test this yourself by manually setting the time a couple of minutes behind or ahead of the actual time and running the command again. In most user cases this is not a big difference and is barely noticeable, but it is more accurate and therefore it should be used.
If you have any questions feel free to ask them.

**Comment by Chensokheng** [comment]
@Daanisaanwezig  I will take a look at that. Thank you very much.

**Comment by Chensokheng** [comment]
@Daanisaanwezig I have checked it. In this project  the version of ``` discord.js is ^11.5.1```. So we can not do ```.ws.ping```.

then I have tried to upgrade the version of the ```discord.js```. But there are some bugs 🐛  when I was upgrade that.

1. ```snekfetch``` is not include in ```discord.js^12.3.1```. So we need to install ```snekfetch``` separately.
2.  ```js
new Discord.RichEmbed() -> change to new Discord.MessageEmbed()
```
3. some command is not working due to the update of the package.

Do you want to upgrade version of discord ? maybe I can give a try and make a new PR. 👩‍💻

**Comment by Chensokheng** [comment]
@Daanisaanwezig If we don't want to update the ```discord.js```. For the current  version of discord.js  to get API latency, we can use  ```bot/client.ping```. if you prefer this way, I will make the change. 🙏

**Comment by Daanisaanwezig** [comment]
Ah, sorry for the inconvenience. `bot.ping` should do the same so feel free to pick that one. If you want to update the bot to Discord.js v12 you can do that and open a new PR for it.

**Comment by Chensokheng** [comment]
@Daanisaanwezig  I have updated the PR. I didn't update the discord.js. I used ```bing.ping```. You can check it. 🙏
 
Happy Hacktoberfest. 👩‍💻

**Comment by Chensokheng** [comment]
@Daanisaanwezig Could you accept this PR ? 🙏

**Pull request merged**
