### PR TITLE
Fix #6

### LINKED ISSUE #6: The serverinfo command does not give correct information
## What is the problem
The ['serverinfo'](https://github.com/Daanisaanwezig/mrMeeseeks/blob/master/commands/moderation/serverinfo.js) command is printing out wrong information on both the user count and role count.

### Expected behavior
Currently the user count includes the bots while they should be displayed in their own field, and the roles includes @ everyone while that role should be excluded.

### PR DESCRIPTION
**Pull request by RicardoQLG**
Fix information os serverinfo command

Captura de tela de 2020-10-03 09-54-04

### CODE REVIEW

**Comment by Daanisaanwezig** [comment]
Hey thanks for the fix, but instead of the role count I would like to see a list of all roles but without the @ everyone role.

**Comment by RicardoQLG** [comment]
> Hey thanks for the fix, but instead of the role count I would like to see a list of all roles but without the @ everyone role.

 Sorry for not including that in my PR. I'm away from the PC at the moment, but I will do it as soon as possible.

**Comment by RicardoQLG** [comment]
English isn't my native language and I appreciate if you can give me a feedback.

Captura de tela de 2020-10-03 23-38-58

**Comment by Daanisaanwezig** [comment]
Hey I think there was a small misunderstanding. How I would like it to be is that let's say you have a server with these 4 roles: admin, helper, muted and member. I want it to show those roles in that order (from highest role to lowest). So it should show:
`Roles: @ admin, @ helper, @ muted, @member`

If you need any help with this feel free to let me know. If you can't get it to work or don't have time to also feel free to let me know and I will merge it regardless.

**Comment by RicardoQLG** [comment]
That is my fault. I need to improve my communications skills and this PR is a good opportunity.

Here the command output:
Captura de tela de 2020-10-04 17-52-51

Here my server role:
Captura de tela de 2020-10-04 17-53-17

In this case I have created Sub Admin after Helper and change order in Discord options.

Is that right or did you think another way?

**Review by Daanisaanwezig — APPROVED** [review]
Should be good to go! I will merge it with the main branch. Thanks for the help!

**Pull request merged**
